# Generated by Django 4.0.3 on 2024-06-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_seshatprivatecommentpart_private_comment_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='seshatprivatecommentpart',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
