# Generated by Django 4.0.3 on 2024-06-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_seshatprivatecommentpart_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seshatprivatecommentpart',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
