# Generated by Django 4.0.3 on 2024-07-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_videoshapefile_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='polity',
            options={'ordering': ['long_name'], 'verbose_name': 'polity', 'verbose_name_plural': 'polities'},
        ),
        migrations.AddField(
            model_name='videoshapefile',
            name='components',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videoshapefile',
            name='member_of',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
