# Generated by Django 4.0.3 on 2024-08-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_country_options_alter_polity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seshatprivatecommentpart',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reference',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seshatprivatecommentpart',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
