# Generated by Django 4.0.3 on 2024-07-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_country_options_alter_polity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoshapefile',
            name='components',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='videoshapefile',
            name='member_of',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
