# Generated by Django 4.0.3 on 2024-09-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_reference_item_type_seshatprivatecommentpart_is_done_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoShapefile',
            new_name='Cliopatria',
        ),
    ]
